draft-ietf-rtcweb-security-arch.xml
I've found a few typos and fixed some sentences that didn't quite make sense.  I don't think the meaning has been changed in any significant way.
=> Typos and minor phrasing corrections

.gitignore, draft-ietf-rtcweb-security-arch.xml
I also cleaned up the requirements that follow on from this.  I think that those changes are editorial only.
=> Let's use ECDSA

draft-ietf-rtcweb-security-arch.xml
Time to update the date and replace RAI with ART.
=> changing date and area's name

draft-ietf-rtcweb-security-arch.xml
Pretty sure we'll get a GEN-ART reviewing say to not refer to the WG by name because it will get closed at some point.  I basically stole the intro from overview and modified it slightly.
=> Tweaking abstract.

draft-ietf-rtcweb-security-arch.xml
* Remove references to BrowserID
* Remove OPEN ISSUE, since that seems to be closed
* Remove reference non-cryptographic authentication, since that's not used 
* Some clarification about "partly trusted"
* Torbutton -> Tor Browser
=> Minor edits

draft-ietf-rtcweb-security-arch.xml
=> Update reference to RFC7675

draft-ietf-rtcweb-security-arch.xml
Adam noted some outdated references.
=> Updating some references

draft-ietf-rtcweb-security-arch.xml
Thinking we can delete the cruft.
=> removing some cruft

draft-ietf-rtcweb-security-arch.xml
=> removing Null from the example in s5.5

draft-ietf-rtcweb-security-arch.xml
Just saving some typing because this section will eventually need to match what's in RFC8174.
=> fixing up the terminology paragraph

draft-ietf-rtcweb-security-arch.xml
=> Determining IdP URI

draft-ietf-rtcweb-security-arch.xml
=> Unicode confusables. Fixes #11

draft-ietf-rtcweb-security-arch.xml
This currently uses the fingerprint, but that's just this version.
=> Better define the scope

draft-ietf-rtcweb-security-arch.xml
This is an (lame) attempt to Close #65.  I'm, not sure the text is in the right place even.
@fluffy @ekr @martinthomson @alvestrand PTAL
As far as I know this is the last technical security issue.
=> addressing issue 65

draft-ietf-rtcweb-security-arch.xml
New chapter for the SDP Identity attribute, including offer/answer procedures.
=> SDP Identity attribute procedures added

draft-ietf-rtcweb-security-arch.xml
=> Use U-labels

draft-ietf-rtcweb-security-arch.xml
Address #82.
Wasn't sure if we should reject the connection.
@ekr PTAL
=> prohibiting TLS false start

draft-ietf-rtcweb-security-arch.xml
=> Addressing one of BenK's discuss points

draft-ietf-rtcweb-security-arch.xml
Need to register well-known/idp-proxy.
=> ad_alexey_idp-proxy_registration

draft-ietf-rtcweb-security-arch.xml
Changes based on [Ben's comments](https://mailarchive.ietf.org/arch/msg/rtcweb/mDXe6mxzyWXAi-_b_u7-0o86mJQ).
=> Addressing Ben Campbell's IESG Review Comments
